publishdir = "public"
baseURL = "https://yanghairui.life"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
title = "Website of Harry Yang"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true 
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
disableThemeSwitcher = true
title = "Per aspera ad astra."
author = "Harry Yang"
copyright = "2020-2021"
description = "Harry Yang's blog"
profilePicture = "images/profile5.jpg"
keywords = "tech/life"
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
#images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = true # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-stack-overflow"
title = "Linkedin"
url = "https://stackoverflow.com/users/12924262/horace-yang"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/harryyann"

[[params.socialIcons]]
icon = "fab fa-zhihu"
title = "zhihu"
url = "https://www.zhihu.com/people/yang-hai-rui-88"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=941811450@qq.com"

## Menu items

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Pictures"
  weight = 300
  identifier = "pictures"
  url = "/pictures/"

  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 500
  identifier = "contact"
  url = "/contact/"


[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]